
package br.com.angeloni.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ResultItemErrorInfo", targetNamespace = "http://ws.integration.angeloni.com.br/")
public class ResultItemErrorInfo_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ResultItemErrorInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ResultItemErrorInfo_Exception(String message, ResultItemErrorInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ResultItemErrorInfo_Exception(String message, ResultItemErrorInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.angeloni.ws.ResultItemErrorInfo
     */
    public ResultItemErrorInfo getFaultInfo() {
        return faultInfo;
    }

}
