
package br.com.angeloni.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VersionedAssets", targetNamespace = "http://ws.integration.angeloni.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VersionedAssets {


    /**
     * 
     * @param productId
     * @return
     *     returns br.com.angeloni.ws.ProductSkuMediasInfo
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductName", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetProductName")
    @ResponseWrapper(localName = "getProductNameResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetProductNameResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/getProductNameRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/getProductNameResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getProductName/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getProductName/Fault/ResultMessageErrorInfo")
    })
    public ProductSkuMediasInfo getProductName(
        @WebParam(name = "productId", targetNamespace = "")
        String productId)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param date
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastChangedProducts", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetLastChangedProducts")
    @ResponseWrapper(localName = "getLastChangedProductsResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetLastChangedProductsResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/getLastChangedProductsRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/getLastChangedProductsResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getLastChangedProducts/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getLastChangedProducts/Fault/ResultMessageErrorInfo")
    })
    public List<String> getLastChangedProducts(
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuSalesCostByStore", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuSalesCostByStore")
    @ResponseWrapper(localName = "syncSkuSalesCostByStoreResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuSalesCostByStoreResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostByStoreRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostByStoreResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostByStore/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostByStore/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuSalesCostByStore(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuSalesCostByStoreInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param skuProductRecipes
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncProductRecipesInSku", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductRecipesInSku")
    @ResponseWrapper(localName = "syncProductRecipesInSkuResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductRecipesInSkuResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipesInSkuRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipesInSkuResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipesInSku/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipesInSku/Fault/ResultMessageErrorInfo")
    })
    public String syncProductRecipesInSku(
        @WebParam(name = "skuProductRecipes", targetNamespace = "")
        SkuProductsRecipeInfo skuProductRecipes)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param productId
     * @param siteId
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLongDescriptionBySite", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetLongDescriptionBySite")
    @ResponseWrapper(localName = "getLongDescriptionBySiteResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetLongDescriptionBySiteResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/getLongDescriptionBySiteRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/getLongDescriptionBySiteResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getLongDescriptionBySite/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/getLongDescriptionBySite/Fault/ResultMessageErrorInfo")
    })
    public String getLongDescriptionBySite(
        @WebParam(name = "productId", targetNamespace = "")
        String productId,
        @WebParam(name = "siteId", targetNamespace = "")
        String siteId)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncLongDescriptionBySite", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncLongDescriptionBySite")
    @ResponseWrapper(localName = "syncLongDescriptionBySiteResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncLongDescriptionBySiteResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncLongDescriptionBySiteRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncLongDescriptionBySiteResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncLongDescriptionBySite/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncLongDescriptionBySite/Fault/ResultMessageErrorInfo")
    })
    public String syncLongDescriptionBySite(
        @WebParam(name = "dataRequest", targetNamespace = "")
        LongDescriptionInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncPackageDimensions", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPackageDimensions")
    @ResponseWrapper(localName = "syncPackageDimensionsResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPackageDimensionsResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPackageDimensionsRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPackageDimensionsResponse", fault = {
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPackageDimensions/Fault/ResultMessageErrorInfo"),
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPackageDimensions/Fault/ResultItemErrorInfo")
    })
    public String syncPackageDimensions(
        @WebParam(name = "dataRequest", targetNamespace = "")
        PackageInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncProduct", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProduct")
    @ResponseWrapper(localName = "syncProductResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProduct/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProduct/Fault/ResultMessageErrorInfo")
    })
    public String syncProduct(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ProductInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncProductCategory", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductCategory")
    @ResponseWrapper(localName = "syncProductCategoryResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductCategoryResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductCategoryRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductCategoryResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductCategory/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductCategory/Fault/ResultMessageErrorInfo")
    })
    public String syncProductCategory(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ProductCategoryInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncBeverageProduct", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncBeverageProduct")
    @ResponseWrapper(localName = "syncBeverageProductResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncBeverageProductResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageProductRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageProductResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageProduct/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageProduct/Fault/ResultMessageErrorInfo")
    })
    public String syncBeverageProduct(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ProductBeverageInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSku", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSku")
    @ResponseWrapper(localName = "syncSkuResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSku/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSku/Fault/ResultMessageErrorInfo")
    })
    public String syncSku(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncBeverageSku", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncBeverageSku")
    @ResponseWrapper(localName = "syncBeverageSkuResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncBeverageSkuResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageSkuRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageSkuResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageSku/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncBeverageSku/Fault/ResultMessageErrorInfo")
    })
    public String syncBeverageSku(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuBeverageInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param replaceFeatures
     * @param productId
     * @param productFeature
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncFeature", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncFeature")
    @ResponseWrapper(localName = "syncFeatureResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncFeatureResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncFeatureRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncFeatureResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncFeature/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncFeature/Fault/ResultMessageErrorInfo")
    })
    public String syncFeature(
        @WebParam(name = "productFeature", targetNamespace = "")
        List<ProductFeature> productFeature,
        @WebParam(name = "productId", targetNamespace = "")
        String productId,
        @WebParam(name = "replaceFeatures", targetNamespace = "")
        Boolean replaceFeatures)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns br.com.angeloni.ws.ResultPriceListInfo
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncPriceList", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPriceList")
    @ResponseWrapper(localName = "syncPriceListResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPriceListResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPriceListRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPriceListResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPriceList/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPriceList/Fault/ResultMessageErrorInfo")
    })
    public ResultPriceListInfo syncPriceList(
        @WebParam(name = "dataRequest", targetNamespace = "")
        PriceListInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param priceListId
     * @param moreInformations
     * @param skuId
     * @return
     *     returns java.util.List<br.com.angeloni.ws.PriceInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrice", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetPrice")
    @ResponseWrapper(localName = "getPriceResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.GetPriceResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/getPriceRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/getPriceResponse")
    public List<PriceInfo> getPrice(
        @WebParam(name = "skuId", targetNamespace = "")
        String skuId,
        @WebParam(name = "priceListId", targetNamespace = "")
        String priceListId,
        @WebParam(name = "moreInformations", targetNamespace = "")
        Boolean moreInformations);

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuMediasSet", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuMediasSet")
    @ResponseWrapper(localName = "syncSkuMediasSetResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuMediasSetResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuMediasSetRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuMediasSetResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuMediasSet/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuMediasSet/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuMediasSet(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuMediaSetInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncPamhplet", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPamhplet")
    @ResponseWrapper(localName = "syncPamhpletResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncPamhpletResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPamhpletRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPamhpletResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPamhplet/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncPamhplet/Fault/ResultMessageErrorInfo")
    })
    public String syncPamhplet(
        @WebParam(name = "dataRequest", targetNamespace = "")
        PamphletInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuSalesCost", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuSalesCost")
    @ResponseWrapper(localName = "syncSkuSalesCostResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuSalesCostResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCostResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCost/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuSalesCost/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuSalesCost(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuSalesCostInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncProductLoose", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductLoose")
    @ResponseWrapper(localName = "syncProductLooseResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductLooseResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductLooseRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductLooseResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductLoose/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductLoose/Fault/ResultMessageErrorInfo")
    })
    public String syncProductLoose(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ProductLooseInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuLoose", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuLoose")
    @ResponseWrapper(localName = "syncSkuLooseResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuLooseResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuLooseRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuLooseResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuLoose/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuLoose/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuLoose(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuLooseInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuBundleLinks", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuBundleLinks")
    @ResponseWrapper(localName = "syncSkuBundleLinksResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuBundleLinksResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuBundleLinksRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuBundleLinksResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuBundleLinks/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuBundleLinks/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuBundleLinks(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuBundleLinkInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncDotz", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncDotz")
    @ResponseWrapper(localName = "syncDotzResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncDotzResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncDotzRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncDotzResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncDotz/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncDotz/Fault/ResultMessageErrorInfo")
    })
    public String syncDotz(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuDotzInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncProductRecipe", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductRecipe")
    @ResponseWrapper(localName = "syncProductRecipeResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncProductRecipeResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipeRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipeResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipe/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncProductRecipe/Fault/ResultMessageErrorInfo")
    })
    public String syncProductRecipe(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ProductRecipeInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuRecipe", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuRecipe")
    @ResponseWrapper(localName = "syncSkuRecipeResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuRecipeResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuRecipeRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuRecipeResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuRecipe/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuRecipe/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuRecipe(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuRecipeInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncListIngredients", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncListIngredients")
    @ResponseWrapper(localName = "syncListIngredientsResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncListIngredientsResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncListIngredientsRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncListIngredientsResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncListIngredients/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncListIngredients/Fault/ResultMessageErrorInfo")
    })
    public String syncListIngredients(
        @WebParam(name = "dataRequest", targetNamespace = "")
        ListIngredientsInfo dataRequest)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setMaxQuantityBuy", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SetMaxQuantityBuy")
    @ResponseWrapper(localName = "setMaxQuantityBuyResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SetMaxQuantityBuyResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/setMaxQuantityBuyRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/setMaxQuantityBuyResponse")
    public String setMaxQuantityBuy(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuMaximumBuyInfo dataRequest);

    /**
     * 
     * @param dataRequest
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setEAN", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SetEAN")
    @ResponseWrapper(localName = "setEANResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SetEANResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/setEANRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/setEANResponse")
    public String setEAN(
        @WebParam(name = "dataRequest", targetNamespace = "")
        SkuEanInfo dataRequest);

    /**
     * 
     * @param skuWithdrawStore
     * @return
     *     returns java.lang.String
     * @throws ResultItemErrorInfo_Exception
     * @throws ResultMessageErrorInfo_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "syncSkuWithdrawStore", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuWithdrawStore")
    @ResponseWrapper(localName = "syncSkuWithdrawStoreResponse", targetNamespace = "http://ws.integration.angeloni.com.br/", className = "br.com.angeloni.ws.SyncSkuWithdrawStoreResponse")
    @Action(input = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuWithdrawStoreRequest", output = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuWithdrawStoreResponse", fault = {
        @FaultAction(className = ResultItemErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuWithdrawStore/Fault/ResultItemErrorInfo"),
        @FaultAction(className = ResultMessageErrorInfo_Exception.class, value = "http://ws.integration.angeloni.com.br/VersionedAssets/syncSkuWithdrawStore/Fault/ResultMessageErrorInfo")
    })
    public String syncSkuWithdrawStore(
        @WebParam(name = "skuWithdrawStore", targetNamespace = "")
        SkuWithdrawStoreInfo skuWithdrawStore)
        throws ResultItemErrorInfo_Exception, ResultMessageErrorInfo_Exception
    ;

}
