
package br.com.angeloni.ws;

import org.springframework.ui.Model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "versionedAssets", targetNamespace = "http://ws.integration.angeloni.com.br/", wsdlLocation = "file:/u/JavaPrecLote/wsdl/versionedAssets.wsdl")
public class VersionedAssets_Service
    extends Service
{

    private final static URL VERSIONEDASSETS_WSDL_LOCATION;
    private final static WebServiceException VERSIONEDASSETS_EXCEPTION;
    private final static QName VERSIONEDASSETS_QNAME = new QName("http://ws.integration.angeloni.com.br/", "versionedAssets");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:C:\\Users\\weliton.villain\\Documents\\Development\\Intellij\\precificacao\\src\\main\\resources\\wsdl\\versionedAssets.wsdl");
            url = new URL("file:/u/JavaPrecLote/wsdl/versionedAssets.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERSIONEDASSETS_WSDL_LOCATION = url;
        VERSIONEDASSETS_EXCEPTION = e;
    }

    public VersionedAssets_Service() {
        super(__getWsdlLocation(), VERSIONEDASSETS_QNAME);
    }

    public VersionedAssets_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERSIONEDASSETS_QNAME, features);
    }

    public VersionedAssets_Service(URL wsdlLocation) {
        super(wsdlLocation, VERSIONEDASSETS_QNAME);
    }

    public VersionedAssets_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERSIONEDASSETS_QNAME, features);
    }

    public VersionedAssets_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VersionedAssets_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VersionedAssets
     */
    @WebEndpoint(name = "VersionedAssetsPort")
    public VersionedAssets getVersionedAssetsPort() {
        return super.getPort(new QName("http://ws.integration.angeloni.com.br/", "VersionedAssetsPort"), VersionedAssets.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VersionedAssets
     */
    @WebEndpoint(name = "VersionedAssetsPort")
    public VersionedAssets getVersionedAssetsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.integration.angeloni.com.br/", "VersionedAssetsPort"), VersionedAssets.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERSIONEDASSETS_EXCEPTION!= null) {
            throw VERSIONEDASSETS_EXCEPTION;
        }
        return VERSIONEDASSETS_WSDL_LOCATION;
    }

}
