insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Preco DE:','plist1690007');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Preco POR','plist1690009');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','ClubeD','plist3200199');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Zoom DE','plist1710021');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Zoom POR','plist1710024');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Buscape DE','plist1710018');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Buscape POR','plist1710025');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','G. Shopping DE','plist1710020');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','G. Shopping POR','plist1710026');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Email Mkt DE','plist1710022');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Divvino','53','Email Mkt POR','plist1710023');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Preco DE:','plist10001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Preco POR','plist10002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Zoom DE','plist520020');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Zoom POR','plist520011');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Buscape DE','plist520019');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Buscape POR','plist520008');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','G. Shopping DE','plist520017');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','G. Shopping POR','plist520010');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Email Mkt DE','plist540015');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Eletro','51','Email Mkt POR','plist540016');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Preco DE:','plist2470179');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Preco POR','plist2470180');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Func.','plist3020063');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Sr. Desc.','plist3020064');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Bradescard','plist3020065');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Func. Bradescard','plist4040004');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Sr. Desc. + Brad.','plist3020066');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','6','Email','plist3630003');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Preco DE:','plist2470181');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Preco POR','plist2470182');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Func.','plist3020067');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Sr. Desc.','plist3020068');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Bradescard','plist3020069');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Func. Bradescard','plist4040003');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Sr. Desc. + Brad.','plist3020070');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','7','Email','plist3630002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Preco DE:','plist2470183');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Preco POR','plist2470184');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Func.','plist3020108');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Sr. Desc.','plist3020109');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Bradescard','plist3020110');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Func. Bradescard','plist4040002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Sr. Desc. + Brad.','plist3020111');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','8','Email','plist3630001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Preco DE:','plist2470185');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Preco POR','plist2470186');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Func.','plist3020071');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Sr. Desc.','plist3020072');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Bradescard','plist3020073');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Func. Bradescard','plist4040001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Sr. Desc. + Brad.','plist3020074');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','12','Email','plist3630011');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Preco DE:','plist3700001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Preco POR','plist3700002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Func.','plist3700003');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Sr. Desc.','plist3700005');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Bradescard','plist3700009');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Func. Bradescard','plist3700004');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Sr. Desc. + Brad.','plist3700006');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','13','Email','plist3700008');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Preco DE:','plist2470187');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Preco POR','plist2470188');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Func.','plist3020075');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Sr. Desc.','plist3020076');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Bradescard','plist3020077');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Func. Bradescard','plist4040005');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Sr. Desc. + Brad.','plist3020078');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','14','Email','plist3630004');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Preco DE:','plist2470189');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Preco POR','plist2470190');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Func.','plist3020079');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Sr. Desc.','plist3020080');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Bradescard','plist3020081');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Func. Bradescard','plist4040007');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Sr. Desc. + Brad.','plist3020082');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','15','Email','plist3630006');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Preco DE:','plist2470191');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Preco POR','plist2470192');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Func.','plist3020083');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Sr. Desc.','plist3020085');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Bradescard','plist3020086');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Func. Bradescard','plist4040009');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Sr. Desc. + Brad.','plist3020087');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','16','Email','plist3630008');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Preco DE:','plist2470195');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Preco POR','plist2470196');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Func.','plist3020092');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Sr. Desc.','plist3020093');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Bradescard','plist3020094');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Func. Bradescard','plist4040011');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Sr. Desc. + Brad.','plist3020095');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','21','Email','plist3630009');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Preco DE:','plist2470197');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Preco POR','plist2470198');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Func.','plist3020096');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Sr. Desc.','plist3020097');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Bradescard','plist3020098');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Func. Bradescard','plist4040012');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Sr. Desc. + Brad.','plist3020099');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','22','Email','plist3630010');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Preco DE:','plist2470199');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Preco POR','plist2470200');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Func.','plist3020100');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Sr. Desc.','plist3020101');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Bradescard','plist3020102');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Func. Bradescard','plist4040006');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Sr. Desc. + Brad.','plist3020103');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','24','Email','plist3630005');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Preco DE:','plist2470201');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Preco POR','plist2470202');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Func.','plist3020104');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Sr. Desc.','plist3020105');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Bradescard','plist3020106');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Func. Bradescard','plist4040008');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Sr. Desc. + Brad.','plist3020107');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','26','Email','plist3630007');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Preco DE:','plist3730001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Preco POR','plist3730002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Func.','plist3730003');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Sr. Desc.','plist3730005');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Bradescard','plist3730006');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Func. Bradescard','plist3730004');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Sr. Desc. + Brad.','plist3730008');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','27','Email','plist3730007');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Preco DE:','plist3670001');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Preco POR','plist3670002');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Func.','plist3670003');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Sr. Desc.','plist3670005');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Bradescard','plist3670006');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Func. Bradescard','plist3670004');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Sr. Desc. + Brad.','plist3670009');
insert into codigo_lista_precos(id,tipo,loja,nome,codigo) values(sys_guid(),'Super','28','Email','plist3670008');


